### ISSUE TITLE
improve styling

### ISSUE THREAD

**Issue by bysimo** [bysimo/sopiler#2]
You can add css code or other code to contribute

**Comment by guisantosfr** [comment]
Assign me please!

**Comment by bysimo** [comment]
@guisantosfr nice work :)

**Comment by slzakaria** [comment]
Heyo ! can restyle the page using bootstrap 5 and make it morenish ! lemme know if you're interessted so i can start on it

**Comment by bysimo** [comment]
@Zackaria-Slimane yeah, sure. but try to avoid too much unused code ok

**Comment by slzakaria** [comment]
Will do !
