### ISSUE TITLE
refactor so that the embedded youtube video size becomes responsive

### ISSUE THREAD

**Issue by bysimo** [bysimo/sopiler#24]
refactor the generated youtube embed video code so that the video size becomes responsive

**Comment by ishaanbedi** [comment]
Hi! Can I work on this?

**Comment by bysimo** [comment]
@ishaanbedi Hi, sorry I see someone else has submitted a Pull Request. Try another issue or create a new issue (if any). Thank you ^__^

**Comment by ishaanbedi** [comment]
Sure! No problem. Looking forward to contributing to other issues.
