### ISSUE TITLE
add storybook js

### ISSUE THREAD

**Issue by bysimo** [bysimo/sopiler#29]

**Comment by codeDude64** [comment]
Is it just adding the storybook setup?

**Comment by bysimo** [comment]
@codeDude64 yes that's right

**Comment by codeDude64** [comment]
> @codeDude64 yes that's right

Could you assign this issue to me?

**Comment by codeDude64** [comment]
Ok I just figured out that I've been assigned to this issue, I started to work on this morning

**Comment by bysimo** [comment]
@codeDude64 Okay, happy coding
