### ISSUE TITLE
[FEAT] : Add an animated toast message while copying embeded text code. 

### ISSUE THREAD

**Issue by nirajpdn** [bysimo/sopiler#31]
There is default javascript alert message while copying text.

<img width="452" alt="Screen Shot 2022-10-17 at 09 41 45" src="https://user-images.githubusercontent.com/59108522/196086146-297ffa12-d0c5-4180-8d88-1a589e7d3764.png">

Replace it with custom animated toast message or can use light toast package similar to this.

<img width="452" alt="Screen Shot 2022-10-17 at 09 41 45" src="https://raw.githubusercontent.com/stla/shinyToastify/main/inst/screenshots/toastTransitions.gif">

@bysimo , what's your take on this ?

**Comment by bysimo** [comment]
@nirajpdn that's great, I assigned it to you

**Comment by nirajpdn** [comment]
@bysimo Sure
