### ISSUE TITLE
change website to react

### ISSUE THREAD

**Issue by LuizHAP** [bysimo/sopiler#8]
@bysimo can I create a new version of this repo on react?

**Comment by bysimo** [comment]
@LuizHAP yeah sure

**Comment by LuizHAP** [comment]
Assign to me and add the hacktoberfest label, please @bysimo

**Comment by LuizHAP** [comment]
@bysimo I fixed this. Can you approve?

**Comment by bysimo** [comment]
@LuizHAP done
